language: java
cache:
  directories:
    - $HOME/.gradle/caches/

deploy:
    provider: script
    script:
        - source build/mew.version.conf && build/deploy.sh $TRAVIS_BRANCH
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^dev|master$
